/**
 * generated by Xtext 2.23.0
 */
package co7217.mu6.entity.domainDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see co7217.mu6.entity.domainDSL.DomainDSLPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
