/*
 * generated by Xtext 2.23.0
 */
package co7217.mu6.entity.ide;

import co7217.mu6.entity.DomainDSLRuntimeModule;
import co7217.mu6.entity.DomainDSLStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DomainDSLIdeSetup extends DomainDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DomainDSLRuntimeModule(), new DomainDSLIdeModule()));
	}
	
}
