/*
 * generated by Xtext 2.23.0
 */
package co7217.xtext.entity.web;

import co7217.xtext.entity.EntityDSLRuntimeModule;
import co7217.xtext.entity.EntityDSLStandaloneSetup;
import co7217.xtext.entity.ide.EntityDSLIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class EntityDSLWebSetup extends EntityDSLStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EntityDSLRuntimeModule(), new EntityDSLIdeModule(), new EntityDSLWebModule()));
	}
	
}
