/*
 * generated by Xtext 2.23.0
 */
package co7217.xtext.entity.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class EntityDSLWebModule extends AbstractEntityDSLWebModule {
}
