/**
 * generated by Xtext 2.23.0
 */
package co7217.xtext.entity.entityDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see co7217.xtext.entity.entityDSL.EntityDSLPackage#getAbstractElement()
 * @model
 * @generated
 */
public interface AbstractElement extends EObject
{
} // AbstractElement
