/**
 * generated by Xtext 2.23.0
 */
package co7217.xtext.entity.entityDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co7217.xtext.entity.entityDSL.Feature#getModifier <em>Modifier</em>}</li>
 *   <li>{@link co7217.xtext.entity.entityDSL.Feature#isMany <em>Many</em>}</li>
 *   <li>{@link co7217.xtext.entity.entityDSL.Feature#getName <em>Name</em>}</li>
 *   <li>{@link co7217.xtext.entity.entityDSL.Feature#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see co7217.xtext.entity.entityDSL.EntityDSLPackage#getFeature()
 * @model
 * @generated
 */
public interface Feature extends EObject
{
  /**
   * Returns the value of the '<em><b>Modifier</b></em>' attribute.
   * The literals are from the enumeration {@link co7217.xtext.entity.entityDSL.Visibility}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modifier</em>' attribute.
   * @see co7217.xtext.entity.entityDSL.Visibility
   * @see #setModifier(Visibility)
   * @see co7217.xtext.entity.entityDSL.EntityDSLPackage#getFeature_Modifier()
   * @model
   * @generated
   */
  Visibility getModifier();

  /**
   * Sets the value of the '{@link co7217.xtext.entity.entityDSL.Feature#getModifier <em>Modifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Modifier</em>' attribute.
   * @see co7217.xtext.entity.entityDSL.Visibility
   * @see #getModifier()
   * @generated
   */
  void setModifier(Visibility value);

  /**
   * Returns the value of the '<em><b>Many</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Many</em>' attribute.
   * @see #setMany(boolean)
   * @see co7217.xtext.entity.entityDSL.EntityDSLPackage#getFeature_Many()
   * @model
   * @generated
   */
  boolean isMany();

  /**
   * Sets the value of the '{@link co7217.xtext.entity.entityDSL.Feature#isMany <em>Many</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Many</em>' attribute.
   * @see #isMany()
   * @generated
   */
  void setMany(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see co7217.xtext.entity.entityDSL.EntityDSLPackage#getFeature_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link co7217.xtext.entity.entityDSL.Feature#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(Type)
   * @see co7217.xtext.entity.entityDSL.EntityDSLPackage#getFeature_Type()
   * @model
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link co7217.xtext.entity.entityDSL.Feature#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

} // Feature
