/**
 * generated by Xtext 2.23.0
 */
package co7217.xtext.entity.entityDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co7217.xtext.entity.entityDSL.Literal#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see co7217.xtext.entity.entityDSL.EntityDSLPackage#getLiteral()
 * @model
 * @generated
 */
public interface Literal extends Type
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see co7217.xtext.entity.entityDSL.EntityDSLPackage#getLiteral_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link co7217.xtext.entity.entityDSL.Literal#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // Literal
