/**
 * generated by Xtext 2.23.0
 */
package co7217.xtext.entity.entityDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see co7217.xtext.entity.entityDSL.EntityDSLPackage#getType()
 * @model
 * @generated
 */
public interface Type extends AbstractElement
{
} // Type
