/*
 * generated by Xtext 2.23.0
 */
package co7217.mu6.entity.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link DomainDSLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractDomainDSLWebModule extends DefaultWebModule {

}
