/*
 * generated by Xtext 2.23.0
 */
package co7217.xtext.entity.ide;

import co7217.xtext.entity.EntityDSLRuntimeModule;
import co7217.xtext.entity.EntityDSLStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EntityDSLIdeSetup extends EntityDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EntityDSLRuntimeModule(), new EntityDSLIdeModule()));
	}
	
}
