/*
 * generated by Xtext 2.23.0
 */
package co7217.mu6.entity;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DomainDSLStandaloneSetup extends DomainDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new DomainDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
