/*
 * generated by Xtext 2.23.0
 */
package co7217.mu6.entity.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class DomainDSLWebModule extends AbstractDomainDSLWebModule {
}
