/*
 * generated by Xtext 2.23.0
 */
package co7217.xtext.entity;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntityDSLRuntimeModule extends AbstractEntityDSLRuntimeModule {
}
