/*
 * generated by Xtext 2.23.0
 */
package co7217.mu6.entity.parser.antlr;

import co7217.mu6.entity.parser.antlr.internal.InternalDomainDSLParser;
import co7217.mu6.entity.services.DomainDSLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DomainDSLParser extends AbstractAntlrParser {

	@Inject
	private DomainDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDomainDSLParser createParser(XtextTokenStream stream) {
		return new InternalDomainDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DomainModel";
	}

	public DomainDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DomainDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
