/**
 * generated by Xtext 2.23.0
 */
package co7217.xtext.entity.entityDSL.impl;

import co7217.xtext.entity.entityDSL.EntityDSLPackage;
import co7217.xtext.entity.entityDSL.Type;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TypeImpl extends AbstractElementImpl implements Type
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EntityDSLPackage.Literals.TYPE;
  }

} //TypeImpl
