/*
 * generated by Xtext 2.23.0
 */
package co7217.mu6.entity.tests

import co7217.mu6.entity.domainDSL.DomainModel
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(DomainDSLInjectorProvider)
class DomainDSLParsingTest {
	@Inject
	ParseHelper<DomainModel> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
datatype String

package RentACar {

	entity Car {
		drivingPlate : String
	}

}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
