/**
 * generated by Xtext 2.23.0
 */
package co7217.mu6.entity.domainDSL.impl;

import co7217.mu6.entity.domainDSL.DataType;
import co7217.mu6.entity.domainDSL.DomainDSLPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DataTypeImpl extends TypeImpl implements DataType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DomainDSLPackage.Literals.DATA_TYPE;
  }

} //DataTypeImpl
