/*
 * generated by Xtext 2.23.0
 */
package co7217.xtext.entity.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEntityDSLScopeProvider extends DelegatingScopeProvider {
}
